[package]
name = "test_util"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
zip = "7.0.0"
chrono={workspace=true}
dfraw_parser_sqlite_lib = {workspace=true}
dfraw_parser = {workspace=true}

[dependencies.reqwest]
version = "0.13.1"
features = ["blocking"]
