[package]
name = "sqlite_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
rusqlite = { workspace = true, features = ["bundled", "blob"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
dfraw_parser= { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[lints]
workspace = true
