[package]
name = "sqlite_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.43"
rusqlite = { version = "0.38.0", features = ["bundled", "blob"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"

[dependencies.dfraw_parser]
path = "../lib"
version = "0"

[dev-dependencies]
tracing-subscriber = "0.3.0"

[lints]
workspace = true
