[package]
name = "sqlite_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
const_format = "0.2.35"
tracing = "0.1.43"
turso = "0.3.2"

[dependencies.dfraw_parser]
path = "../lib"
version = "0"

[dev-dependencies]
tracing-subscriber = "0.3.0"

[dev-dependencies.pollster]
version = "0.4.0"
features = ["macro"]

[lints]
workspace = true
